from typing import Protocol, runtime_checkable


@runtime_checkable
class TempFS(Protocol):
    """Minimal interface for a temporary filesystem used by log analyzers."""

    def read_text(self, rel_path: str, encoding: str = "utf-8") -> str: ...
    def read_bytes(self, rel_path: str) -> bytes: ...
    def exists(self, rel_path: str) -> bool: ...
    def listdir(self, rel_path: str = "") -> list[str]: ...
    def rglob(self, pattern: str) -> list[str]: ...
